# @package _global_

defaults:
  - _self_
  - datamodule: market.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: metric_learning.yaml
  - logger: many_loggers.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

ckpt_path: models/epoch_120.ckpt
